worlds:
  arena: "Bridge"
  lobby: "world"
lobby-spawn:
  x: 0
  y: -60
  z: 0
powerups:
  health:
    x: -2471.577
    y: 17.5
    z: 697.445
  damage:
    - {x: -2480.476, y: 24.5, z: 697.423}
    - {x: -2462.592, y: 24.5, z: -697.423}