name: ArenaBrawl
version: '1.0'
main: org.latios.arenaBrawl.ArenaBrawlPlugin
api-version: '26.2'
load: POSTWORLD
softdepend: [LibsDisguises]
enable-player-collisions: false
commands:
  party:
    description: Manage your party
    usage: /party <invite|accept|leave> [player]
  queue:
    description: Leave or join the queue
    usage: /queue <join|leave>
  abilities:
    description: Select your abilities
    usage: /abilities
  rating:
    description: Shows a player's rating
    usage: /rating <name>
  leaderboard:
    description: Shows the top 10 highest rated players
    usage: /leaderboard
  capturestructure:
    description: Captures blocks around you into BlockOffset code for a structure blueprint
    usage: /capturestructure [radiusX radiusY radiusZ]
  reloadabilities:
    description: Reloads ability values from config file
    usage: /reloadabilities
  draw:
    description: Vote to end the current match in a draw
    usage: /draw
  addcoins:
    description: Adds coins to a player's balance
    usage: /addcoins <player> <amount>